name: kernel-build
permissions:
  contents: write
  actions: write
on:
  workflow_call:
    inputs:
      proj_name:
        required: true
        type: string
        default: "i915-sriov-dkms"
      target_commit_sha:
        required: true
        type: string
        default: "HEAD"
      target_dkms_version:
        required: true
        type: string
        default: ""
      kernel_name:
        required: true
        type: string
      kernel_ver:
        required: true
        type: string
      container_image:
        required: true
        type: string
      patch_mode:
        required: false
        type: string
        default: ""
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container_image }}
      options: -v ${{ github.workspace }}:${{ github.workspace }}
    steps:
      - name: Check out repository code
        run: |
          git clone https://github.com/GreenDamTan/i915-sriov-dkms.git
          cd i915-sriov-dkms && git reset --hard ${{ inputs.target_commit_sha }}
      - name: Apply legacy 6.6.38 patch
        if: ${{ inputs.patch_mode == 'legacy_6_6_38' }}
        run: |
          sed "s/.require_force_probe = 1,/.require_force_probe = 0,/g" -i i915-sriov-dkms/drivers/gpu/drm/i915/i915_pci.c
          sed "s/max_vfs, 0/max_vfs, 7/g" -i i915-sriov-dkms/drivers/gpu/drm/i915/i915_params.h
      - name: build ko
        id: build_ko
        run: |
          dkms add ./i915-sriov-dkms
          dkms install i915-sriov-dkms/${{ inputs.target_dkms_version }} --verbose
      - name: cat build log
        if: ${{ failure() && steps.build_ko.outcome == 'failure' }}
        run: |
          cat /var/lib/dkms/i915-sriov-dkms/*/build/make.log || true
      - name: copy ko
        run: |
          mkdir -p upload/${{ inputs.proj_name }}_${{ inputs.kernel_name }}
          cp -rf /lib/modules/${{ inputs.kernel_ver }}/updates/dkms/* upload/${{ inputs.proj_name }}_${{ inputs.kernel_name }}/
      - name: upload ko
        uses: actions/upload-artifact@master
        with:
          name: ${{ inputs.proj_name }}-${{ inputs.kernel_name }}
          path: upload
