name: kernel-6.18.18-trim-570-amd64
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions
on:
  workflow_call: # This allows this workflow to be called from another workflow
    inputs:
      proj_name:
        required: true
        type: string
        default: "i915-sriov-dkms"
      target_commit_sha:
        required: true
        type: string
        default: "HEAD"
      target_dkms_version:
        required: true
        type: string
        default: ""
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: makedie/fnos:kernHead-6.18.18-trim-570-amd64
      options: -v ${{ github.workspace }}:${{ github.workspace }}
    env:
      kernel_name: "6.18.18-trim-570-amd64"
      kernel_ver: "6.18.18-trim"
    steps:
      - name: Check out repository code
        run: |
          git clone https://github.com/GreenDamTan/i915-sriov-dkms.git
          cd i915-sriov-dkms && git reset --hard ${{ inputs.target_commit_sha }}
      - name: build ko
        id: build_ko
        run: |
          dkms add ./i915-sriov-dkms
          dkms install i915-sriov-dkms/${{ inputs.target_dkms_version }} --verbose
      - name: cat build log
        if: ${{ failure() && steps.build_ko.outcome == 'failure' }}
        run: |
          cat /var/lib/dkms/i915-sriov-dkms/*/build/make.log || true
      - name: copy ko
        run: |
          mkdir -p upload/${{ inputs.proj_name }}_${{ env.kernel_name }}
          cp -rf /lib/modules/${{ env.kernel_ver }}/updates/dkms/* upload/${{ inputs.proj_name }}_${{ env.kernel_name }}/
      - name: upload ko
        uses: actions/upload-artifact@master
        with:
          name: ${{ inputs.proj_name }}-${{ env.kernel_name }}
          path: upload
